// AUTO-GENERATED by `npm run gen:api` from the FastAPI OpenAPI schema.
// Do not hand-edit — run `npm run gen:api` after changing eda_rl/api/.

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Designs */
        get: operations["designs_api_designs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{design}/{platform}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Summary */
        get: operations["campaign_summary_api_campaigns__design___platform__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{design}/{platform}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Episodes */
        get: operations["campaign_episodes_api_campaigns__design___platform__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{design}/{platform}/pareto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Pareto */
        get: operations["campaign_pareto_api_campaigns__design___platform__pareto_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{design}/{platform}/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Funnel */
        get: operations["campaign_funnel_api_campaigns__design___platform__funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{design}/{platform}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign History */
        get: operations["campaign_history_api_campaigns__design___platform__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{design}/{platform}/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Best */
        get: operations["campaign_best_api_campaigns__design___platform__best_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{design}/{platform}/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Baseline */
        get: operations["campaign_baseline_api_campaigns__design___platform__baseline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BaselineOut */
        BaselineOut: {
            /** Earliest F3 */
            earliest_f3: {
                [key: string]: unknown;
            } | null;
            /** Hand Picked Baseline */
            hand_picked_baseline: {
                [key: string]: unknown;
            } | null;
        };
        /** BestConfigOut */
        BestConfigOut: {
            /** Badge */
            badge: string;
            /** Sublabel */
            sublabel: string;
            /** Variant */
            variant: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Obs */
            obs: {
                [key: string]: unknown;
            };
            /** Score */
            score: number | null;
        };
        /** CampaignSummary */
        CampaignSummary: {
            /** Design */
            design: string;
            /** Platform */
            platform: string;
            /** Campaign Id */
            campaign_id: string;
            /** N Episodes */
            n_episodes: number;
            fidelity_counts: components["schemas"]["FunnelCounts"];
            /** Best Value */
            best_value: number | null;
            /** Params */
            params: {
                [key: string]: components["schemas"]["ParamSpecOut"];
            };
        };
        /** DesignPlatformPair */
        DesignPlatformPair: {
            /** Design */
            design: string;
            /** Platform */
            platform: string;
        };
        /** FunnelCounts */
        FunnelCounts: {
            /** F0 */
            F0: number;
            /** F1 */
            F1: number;
            /** F2 */
            F2: number;
            /** F3 */
            F3: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Episode */
            episode: number | null;
            /** Ts */
            ts: number | null;
            /** Value */
            value: number | null;
            /** Running Max */
            running_max: number | null;
        };
        /** ParamSpecOut */
        ParamSpecOut: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Choices */
            choices: string[];
        };
        /** ParetoPoint */
        ParetoPoint: {
            /** Area Um2 */
            area_um2: number;
            /** Fmax Mhz */
            fmax_mhz: number;
            /** Is Frontier */
            is_frontier: boolean;
            /** Row */
            row: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    designs_api_designs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignPlatformPair"][];
                };
            };
        };
    };
    campaign_summary_api_campaigns__design___platform__get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path: {
                design: string;
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_episodes_api_campaigns__design___platform__episodes_get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path: {
                design: string;
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_pareto_api_campaigns__design___platform__pareto_get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path: {
                design: string;
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParetoPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_funnel_api_campaigns__design___platform__funnel_get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path: {
                design: string;
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelCounts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_history_api_campaigns__design___platform__history_get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path: {
                design: string;
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_best_api_campaigns__design___platform__best_get: {
        parameters: {
            query?: {
                campaign?: string | null;
                top?: number;
            };
            header?: never;
            path: {
                design: string;
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_baseline_api_campaigns__design___platform__baseline_get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path: {
                design: string;
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
